<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="proyectomm" nsURI="http://www.example.org/proyectomm" nsPrefix="proyectomm">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eAnnotations source="gmf"/>
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="operationReflection" value="true"/>
    <details key="tableProviders" value="true"/>
    <details key="complianceLevel" value="6.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ProcesoDeNegocio">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="R01_unaTareaInicial R02_unaTareaFinal"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="R01_unaTareaInicial" value="Inicio.allInstances()->size() = 1"/>
      <details key="R02_unaTareaFinal" value="Fin.allInstances()->size() = 1"/>
    </eAnnotations>
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bases_de_datos" lowerBound="1"
        upperBound="-1" eType="#//BaseDeDatos" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actores" lowerBound="1"
        upperBound="-1" eType="#//Actor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="R05_minTareaIntermedia"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="R05_minTareaIntermedia" value="tareas->select(oclIsKindOf(Intermedia))->size() > 0"/>
    </eAnnotations>
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/proyecto/icons/actor.svg"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tareas" upperBound="-1"
        eType="#//Tarea" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="num_tareas" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="self.tareas->size()"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseDeDatos">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/proyecto/icons/database.svg"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tablas" lowerBound="1"
        upperBound="-1" eType="#//Tabla" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tabla">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="P02_soloUnaClavePrimaria P03_clavesTipoInteger"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="P02_soloUnaClavePrimaria" value="&#xA;&#x9;&#x9;        self.atributos->select(a | a.oclIsTypeOf(PrimaryKey))->size() = 1"/>
      <details key="P03_clavesTipoInteger" value="&#xA;&#x9;&#x9;&#x9;    self.atributos->select(a | a.oclIsTypeOf(PrimaryKey) or a.oclIsTypeOf(ForeignKey))&#xA;&#x9;&#x9;&#x9;                 ->forAll(at | at.tipo = EAtributo::INTEGER)"/>
    </eAnnotations>
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/proyecto/icons/table.svg"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributos" lowerBound="1"
        upperBound="-1" eType="#//Atributo" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atributo">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="P01_tieneOpciones P05_sinEspaciosEnBlanco"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="P01_tieneOpciones" value="&#xA;&#x9;&#x9;&#x9;    if self.tipo = EAtributo::LIST then&#xA;&#x9;&#x9;&#x9;        self.opciones->notEmpty()&#xA;&#x9;&#x9;&#x9;    else&#xA;&#x9;&#x9;&#x9;        self.opciones->isEmpty()&#xA;&#x9;&#x9;&#x9;    endif"/>
      <details key="P05_sinEspaciosEnBlanco" value="&#xA;&#x9;&#x9;        not self.nombre->includes(' ')"/>
    </eAnnotations>
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/proyecto/icons/attribute.svg"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" lowerBound="1" eType="#//EAtributo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opciones" upperBound="-1"
        eType="#//Opcion" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EAtributo">
    <eLiterals name="INTEGER"/>
    <eLiterals name="REAL"/>
    <eLiterals name="TEXT"/>
    <eLiterals name="BOOLEAN" value="3"/>
    <eLiterals name="LIST" value="4"/>
    <eLiterals name="DATE" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tarea" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="R06_noReflexiva R08_ConexionesEntreTareas R09_unidireccionalidad"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="R06_noReflexiva" value="sucesor &lt;> self"/>
      <details key="R08_ConexionesEntreTareas" value="&#xA;&#x9;&#x9;  if self.oclIsTypeOf(Envio) then&#xA;&#x9;&#x9;    -- Se evalï¿½a que Envio y Recepcion sean de distinto actor&#xA;&#x9;&#x9;    self.oclContainer() &lt;> self.sucesor.oclContainer() &#xA;&#x9;&#x9;  else&#xA;&#x9;&#x9;    -- El resto de conexiones deben ser del mismo actor&#xA;&#x9;&#x9;    self.sucesor->isEmpty() or&#xA;&#x9;&#x9;    self.sucesor.oclContainer() = self.oclContainer()&#xA;&#x9;&#x9;  endif"/>
      <details key="R09_unidireccionalidad" value="&#xA;&#x9;&#x9;self.predecesor->size() &lt;= 1 and self.sucesor->size() &lt;= 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sucesor" eType="#//Tarea"
        eOpposite="#//Tarea/predecesor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predecesor" eType="#//Tarea"
        eOpposite="#//Tarea/sucesor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inicio" eSuperTypes="#//Tarea">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="R03_sinPredecesor"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="R03_sinPredecesor" value="predecesor = null"/>
    </eAnnotations>
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/proyecto/icons/start.svg"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fin" eSuperTypes="#//Tarea">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="R04_sinSucesor"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="R04_sinSucesor" value="sucesor = null"/>
    </eAnnotations>
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/proyecto/icons/finish.svg"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Intermedia" abstract="true" eSuperTypes="#//Tarea">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descripcion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Usuario" eSuperTypes="#//Intermedia">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/proyecto/icons/form.svg"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tabla_accedida" lowerBound="1"
        eType="#//Tabla"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Servicio" eSuperTypes="#//Intermedia">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/proyecto/icons/service.svg"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tabla_accedida" lowerBound="1"
        eType="#//Tabla"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mensaje" abstract="true" eSuperTypes="#//Intermedia">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tabla_accedida" lowerBound="1"
        eType="#//Tabla"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Envio" eSuperTypes="#//Mensaje">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/proyecto/icons/sent-message.svg"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Recepcion" eSuperTypes="#//Mensaje">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="R07_envioAsociado P06_mismaTablaQueEnvio"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="R07_envioAsociado" value="predecesor.oclIsTypeOf(Envio)"/>
      <details key="P06_mismaTablaQueEnvio" value="self.tabla_accedida = self.predecesor.oclAsType(Envio).tabla_accedida"/>
    </eAnnotations>
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/proyecto/icons/received-message.svg"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Borrado" eSuperTypes="#//BD">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="P04_borradoConClavePrimaria"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="P04_borradoConClavePrimaria" value="&#xA;&#x9;&#x9;        self.atributo_seleccionado.oclIsTypeOf(PrimaryKey)"/>
    </eAnnotations>
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/proyecto/icons/delete.svg"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lectura" eSuperTypes="#//BD">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/proyecto/icons/read.svg"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datos_a_leer" lowerBound="1"
        eType="#//Tabla" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="self.atributo_seleccionado.oclContainer().oclAsType(Tabla)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BD" abstract="true" eSuperTypes="#//Intermedia">
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributo_seleccionado"
        lowerBound="1" eType="#//Atributo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimaryKey" eSuperTypes="#//Atributo">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/proyecto/icons/pk.svg"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForeignKey" eSuperTypes="#//Atributo">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/proyecto/icons/fk.svg"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencia_a" lowerBound="1"
        eType="#//PrimaryKey"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Opcion">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/proyecto/icons/option.svg"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
